[config]

[templates.dykwabigtk4]
input_path = './matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/buck-colors.css'

[templates.dykwabikcolorscheme]
input_path = './matugen/templates/kcolorscheme.colors'
output_path = '~/.local/share/color-schemes/BuckMatugen.colors'

[templates.dykwabilightkcolorscheme]
input_path = './matugen/templates/light-kcolorscheme.colors'
output_path = '~/.local/share/color-schemes/BuckMatugenLight.colors'

[templates.dykwabidarkkcolorscheme]
input_path = './matugen/templates/dark-kcolorscheme.colors'
output_path = '~/.local/share/color-schemes/BuckMatugenDark.colors'