[templates.dykwabikitty]
input_path = './matugen/templates/kitty.conf'
output_path = '~/.config/kitty/buck-theme.conf'

[templates.dykwabikittytabs]
input_path = './matugen/templates/kitty-tabs.conf'
output_path = '~/.config/kitty/buck-tabs.conf'